'use client';

import React, { useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { 
  CheckCircle2, 
  XCircle, 
  Clock, 
  Terminal, 
  Copy, 
  Download, 
  Inbox,
  Check,
  X
} from 'lucide-react';
import { toast } from 'sonner';

export interface TaskRun {
  id: string;
  taskName: string;
  timestamp: string;
  status: 'running' | 'success' | 'failed';
  duration?: number; // in ms
  summary: string;
}

interface TaskInboxPanelProps {
  runs: TaskRun[];
  onViewLogs: (taskName: string) => void;
  onClearRuns: () => void;
  onClose: () => void;
}

export default function TaskInboxPanel({
  runs,
  onViewLogs,
  onClearRuns,
  onClose
}: TaskInboxPanelProps) {
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const handleCopySummary = (id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    toast.success('Summary copied to clipboard!');
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleDownload = (taskName: string) => {
    toast.success(`Downloading report for ${taskName}...`, {
      description: 'Report downloaded successfully.'
    });
  };

  return (
    <div className="w-80 md:w-96 h-full bg-[#F5F5F7] dark:bg-zinc-950 border-l border-black/10 dark:border-zinc-800/80 flex flex-col shrink-0 transition-all duration-300 ease-in-out relative">
      {/* Panel Header */}
      <div className="p-5 bg-white dark:bg-zinc-900 border-b border-black/5 dark:border-zinc-800/80 shrink-0 relative pr-12">
        <div className="flex items-center justify-between">
          <h2 className="text-gray-900 dark:text-white flex items-center gap-2 text-sm font-bold select-none">
            <Inbox className="size-4.5 text-indigo-500" />
            Runs Inbox
          </h2>
          
          <div className="flex items-center gap-2">
            {runs.length > 0 && (
              <Button 
                variant="ghost" 
                size="sm" 
                onClick={onClearRuns}
                className="text-[10px] h-7 px-2 font-bold text-rose-500 hover:text-rose-600 hover:bg-rose-50/50 dark:hover:bg-rose-950/20"
              >
                Clear All
              </Button>
            )}
            
            <button
              onClick={onClose}
              className="p-1 text-gray-400 hover:text-gray-700 dark:hover:text-zinc-200 rounded-lg hover:bg-gray-100 dark:hover:bg-zinc-800 transition-colors"
            >
              <X className="size-4" />
            </button>
          </div>
        </div>
        <p className="text-gray-500 dark:text-zinc-400 text-[10px] mt-1.5 leading-relaxed select-none">
          Monitor execution runs and download report artifacts generated by your automated tasks.
        </p>
      </div>

      {/* Runs Feed */}
      <div className="flex-1 overflow-y-auto p-5 space-y-4">
        {runs.map((run) => (
          <div 
            key={run.id}
            className="bg-white dark:bg-zinc-900 border border-black/5 dark:border-white/5 rounded-2xl p-4 shadow-xs space-y-3.5 hover:shadow-sm transition-shadow duration-300 relative overflow-hidden"
          >
            {run.status === 'running' && (
              <div className="absolute top-0 left-0 right-0 h-1 bg-indigo-500/20 overflow-hidden">
                <div className="h-full bg-indigo-500 animate-[shimmer_1.5s_infinite] w-[40%]" />
              </div>
            )}

            <div className="flex items-start justify-between gap-3">
              <div className="space-y-0.5 flex-1 min-w-0">
                <h3 className="font-semibold text-gray-900 dark:text-white text-xs leading-snug truncate">
                  {run.taskName}
                </h3>
                <p className="text-[9px] text-gray-400 dark:text-zinc-500 font-medium">
                  Run ID: {run.id.slice(0, 8)}
                </p>
              </div>

              <div className="shrink-0">
                {run.status === 'running' ? (
                  <Badge className="bg-indigo-500/10 hover:bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border border-indigo-500/20 rounded-md font-semibold px-1.5 py-0.5 text-[9px] flex gap-1 items-center select-none animate-pulse">
                    <div className="size-1.5 rounded-full bg-indigo-500 animate-ping" />
                    Running
                  </Badge>
                ) : run.status === 'success' ? (
                  <Badge className="bg-emerald-500/10 hover:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20 rounded-md font-semibold px-1.5 py-0.5 text-[9px] flex gap-1 items-center select-none">
                    <CheckCircle2 className="h-2.5 w-2.5" />
                    Success
                  </Badge>
                ) : (
                  <Badge className="bg-rose-500/10 hover:bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/20 rounded-md font-semibold px-1.5 py-0.5 text-[9px] flex gap-1 items-center select-none">
                    <XCircle className="h-2.5 w-2.5" />
                    Failed
                  </Badge>
                )}
              </div>
            </div>

            <div className="text-[11px] text-gray-600 dark:text-zinc-300 leading-relaxed bg-gray-50/50 dark:bg-zinc-950/40 rounded-xl p-3 border border-black/5 dark:border-white/5">
              {run.summary}
            </div>

            <div className="flex flex-wrap items-center justify-between pt-1 gap-2 border-t border-black/5 dark:border-zinc-800/80">
              <div className="flex items-center gap-3 text-[10px] text-gray-400 dark:text-zinc-500">
                <span className="flex items-center gap-1 font-medium">
                  <Clock className="size-3" />
                  {run.duration ? `${(run.duration / 1000).toFixed(1)}s` : '--'}
                </span>
                <span className="font-medium">
                  {new Date(run.timestamp).toLocaleTimeString(undefined, {
                    hour: '2-digit',
                    minute: '2-digit',
                    second: '2-digit'
                  })}
                </span>
              </div>

              <div className="flex items-center gap-1">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => onViewLogs(run.taskName)}
                  className="h-6 px-1.5 rounded-md text-[10px] text-gray-500 dark:text-zinc-400 hover:bg-gray-100 dark:hover:bg-zinc-800 flex items-center gap-1"
                >
                  <Terminal className="size-2.5" />
                  Logs
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => handleCopySummary(run.id, run.summary)}
                  className="h-6 px-1.5 rounded-md text-[10px] text-gray-500 dark:text-zinc-400 hover:bg-gray-100 dark:hover:bg-zinc-800 flex items-center gap-1"
                >
                  {copiedId === run.id ? <Check className="size-2.5 text-emerald-500" /> : <Copy className="size-2.5" />}
                  Copy
                </Button>
                {run.status === 'success' && (
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => handleDownload(run.taskName)}
                    className="h-6 px-1.5 rounded-md text-[10px] text-gray-500 dark:text-zinc-400 hover:bg-gray-100 dark:hover:bg-zinc-800 flex items-center gap-1"
                  >
                    <Download className="size-2.5" />
                    Report
                  </Button>
                )}
              </div>
            </div>
          </div>
        ))}

        {runs.length === 0 && (
          <div className="flex flex-col items-center justify-center text-center p-8 border border-dashed border-black/10 dark:border-white/10 rounded-3xl min-h-[250px] bg-white dark:bg-zinc-900">
            <Inbox className="size-8 text-gray-300 dark:text-zinc-700 mb-2.5 animate-pulse" />
            <h4 className="font-semibold text-xs text-gray-900 dark:text-white mb-1">
              No runs recorded
            </h4>
            <p className="text-[10px] text-gray-500 dark:text-zinc-400 max-w-[180px] leading-relaxed">
              Create an automated task and check this feed for results.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
