'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import {
  ArrowLeft,
  Mail,
  Trash2,
  Search,
  MessageSquare,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogClose,
} from '@/components/ui/dialog';
import { toast } from 'sonner';

interface SupportRequest {
  id: string;
  email: string;
  subject: string;
  message: string;
  date: string;
  time: string;
  status: 'Pending' | 'Responded';
  response?: string;
  respondedAt?: string;
}

const DEFAULT_SUPPORT_REQUESTS: SupportRequest[] = [
  {
    id: 'req-1',
    email: 'alex.jones@gmail.com',
    subject: 'Billing issue with my premium subscription',
    message: "Hi, I was charged twice for this month's premium subscription. Can you please refund the duplicate charge? Thanks.",
    date: 'Jun 7, 2026',
    time: '10:14 AM',
    status: 'Pending',
  },
  {
    id: 'req-2',
    email: 'sarah.smith@designco.io',
    subject: 'API access limits questions',
    message: "Hi support team, we are planning to upgrade our team plan but want to know if there's any hard limit on the number of daily API calls. Looking forward to your reply.",
    date: 'Jun 6, 2026',
    time: '02:30 PM',
    status: 'Pending',
  },
  {
    id: 'req-3',
    email: 'michael.brown@techcorp.com',
    subject: 'Custom guardrail setup assistance',
    message: "Hello, we are trying to configure a custom guardrail to block specific proprietary code snippets from being generated by the assistant. We couldn't find the exact syntax in the documentation. Could you please help us set this up?",
    date: 'Jun 5, 2026',
    time: '11:45 AM',
    status: 'Responded',
    response: "Hello Michael, thanks for reaching out. You can specify proprietary code blocking by adding a regex pattern directly in the Guardrails console. For example, add the pattern to the 'Block list' under configurations. Let us know if you need any further help!",
    respondedAt: 'Jun 5, 2026 01:15 PM',
  },
  {
    id: 'req-4',
    email: 'emily.davis@edu.org',
    subject: 'Educational discount request',
    message: "Hello, I am a research assistant at the university. Do you offer educational discounts for research teams? Thank you.",
    date: 'Jun 4, 2026',
    time: '09:00 AM',
    status: 'Responded',
    response: "Hi Emily, yes we do offer a 50% discount for educational and research institutions. Please provide your official institutional credentials or registration details, and we'll apply it to your account.",
    respondedAt: 'Jun 4, 2026 11:30 AM',
  },
];

export default function AdminSupportInboxPage() {
  const [requests, setRequests] = useState<SupportRequest[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  
  // Dialog state for viewing / responding
  const [viewingRequest, setViewingRequest] = useState<SupportRequest | null>(null);
  const [responseText, setResponseText] = useState('');
  const [isSubmittingResponse, setIsSubmittingResponse] = useState(false);

  // Dialog state for deleting
  const [deletingRequest, setDeletingRequest] = useState<SupportRequest | null>(null);

  useEffect(() => {
    const existing = localStorage.getItem('alti_support_requests');
    if (existing) {
      try {
        setRequests(JSON.parse(existing));
      } catch (e) {
        console.error(e);
        setRequests(DEFAULT_SUPPORT_REQUESTS);
        localStorage.setItem('alti_support_requests', JSON.stringify(DEFAULT_SUPPORT_REQUESTS));
      }
    } else {
      setRequests(DEFAULT_SUPPORT_REQUESTS);
      localStorage.setItem('alti_support_requests', JSON.stringify(DEFAULT_SUPPORT_REQUESTS));
    }
  }, []);

  const handleSendResponse = () => {
    if (!viewingRequest || !responseText.trim()) return;
    setIsSubmittingResponse(true);

    setTimeout(() => {
      const now = new Date();
      const updatedRequests = requests.map(req => {
        if (req.id === viewingRequest.id) {
          return {
            ...req,
            status: 'Responded' as const,
            response: responseText.trim(),
            respondedAt: `${now.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })} ${now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}`,
          };
        }
        return req;
      });

      setRequests(updatedRequests);
      localStorage.setItem('alti_support_requests', JSON.stringify(updatedRequests));
      toast.success(`Response sent successfully to ${viewingRequest.email}`);
      setIsSubmittingResponse(false);
      setViewingRequest(null);
      setResponseText('');
    }, 800);
  };

  const handleDelete = () => {
    if (!deletingRequest) return;
    const updatedRequests = requests.filter(req => req.id !== deletingRequest.id);
    setRequests(updatedRequests);
    localStorage.setItem('alti_support_requests', JSON.stringify(updatedRequests));
    toast.success('Support request removed from inbox.');
    setDeletingRequest(null);
  };

  const filteredRequests = requests.filter(req => {
    const term = searchTerm.toLowerCase().trim();
    return (
      req.email.toLowerCase().includes(term) ||
      req.subject.toLowerCase().includes(term) ||
      req.message.toLowerCase().includes(term)
    );
  });

  return (
    <div className="h-full flex flex-col bg-[#F5F5F7] dark:bg-gray-955 overflow-hidden">
      {/* Header */}
      <div className="h-[52px] border-b border-black/10 dark:border-white/10 flex items-center justify-between px-8 flex-none bg-white dark:bg-gray-955">
        <h1 className="text-base font-semibold text-gray-900 dark:text-white">
          Support
        </h1>
        <Button asChild variant="outline" size="sm">
          <Link href="/admin">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Dashboard
          </Link>
        </Button>
      </div>

      {/* Main Workspace Body */}
      <div className="flex-1 min-h-0 px-8 py-6 overflow-hidden flex flex-col">
        <div className="mx-auto flex w-full max-w-7xl flex-col gap-6 flex-1 min-h-0">
          <div className="flex-1 min-h-0 flex flex-col gap-4">
            
            {/* Search Bar */}
            <div className="relative w-full flex-none">
              <Search className="text-muted-foreground absolute top-1/2 left-4 h-5 w-5 -translate-y-1/2" />
              <Input
                placeholder="Search support requests by email, subject, or message content..."
                value={searchTerm}
                onChange={e => setSearchTerm(e.target.value)}
                className="pl-12 pr-4 h-12 w-full text-base rounded-lg border-black/10 dark:border-white/10 bg-white dark:bg-gray-900 shadow-sm focus-visible:ring-0 focus-visible:ring-offset-0 focus:outline-none focus-visible:outline-none outline-none"
              />
            </div>

            {/* Support Requests List */}
            <div className="flex-1 min-h-0 overflow-y-auto pr-1">
              {filteredRequests.length === 0 ? (
                <div className="text-center p-8 border border-dashed rounded-lg text-muted-foreground text-sm bg-white dark:bg-gray-900">
                  No customer support requests found.
                </div>
              ) : (
                <div className="flex flex-col gap-2 pb-4">
                  {filteredRequests.map((req) => (
                    <div
                      key={req.id}
                      className="grid grid-cols-12 gap-4 px-6 py-3.5 bg-white/90 dark:bg-gray-900/90 border border-black/5 dark:border-white/5 rounded-lg shadow-sm items-center animate-in fade-in-50 duration-150"
                    >
                      {/* Left icon & Content columns */}
                      <div className="col-span-10 flex items-center gap-5 min-w-0">
                        <div className={`h-8 w-8 rounded-lg flex items-center justify-center flex-none ${
                          req.status === 'Pending' 
                            ? 'bg-amber-50 dark:bg-amber-955/20 text-amber-600 dark:text-amber-400' 
                            : 'bg-emerald-50 dark:bg-emerald-955/20 text-emerald-600 dark:text-emerald-400'
                        }`}>
                          <Mail className="h-4 w-4" />
                        </div>
                        
                        <div className="flex-1 flex items-center gap-8 min-w-0">
                          {/* Email */}
                          <div className="flex-[2.5] min-w-0">
                            <span className="text-[9px] font-semibold text-gray-400 dark:text-gray-500 block uppercase tracking-wider mb-0.5 select-none">
                              Email Address
                            </span>
                            <span className="text-sm font-semibold text-gray-800 dark:text-gray-200 truncate block select-all">
                              {req.email}
                            </span>
                          </div>
                          
                          {/* Subject */}
                          <div className="flex-[3.5] min-w-0">
                            <span className="text-[9px] font-semibold text-gray-400 dark:text-gray-500 block uppercase tracking-wider mb-0.5 select-none">
                              Subject
                            </span>
                            <span className="text-sm font-medium text-gray-700 dark:text-gray-300 truncate block">
                              {req.subject}
                            </span>
                          </div>
                          
                          {/* Date */}
                          <div className="flex-[1.5] min-w-0">
                            <span className="text-[9px] font-semibold text-gray-400 dark:text-gray-500 block uppercase tracking-wider mb-0.5 select-none">
                              Date
                            </span>
                            <span className="text-sm text-gray-650 dark:text-gray-400 block mt-0.5 font-medium">
                              {req.date}
                            </span>
                          </div>
                          
                          {/* Time */}
                          <div className="flex-[1.2] min-w-0">
                            <span className="text-[9px] font-semibold text-gray-400 dark:text-gray-500 block uppercase tracking-wider mb-0.5 select-none">
                              Time
                            </span>
                            <span className="text-sm text-gray-650 dark:text-gray-400 block mt-0.5 font-medium">
                              {req.time}
                            </span>
                          </div>

                          {/* Status Badge */}
                          <div className="flex-[1.3] min-w-0">
                            <span className="text-[9px] font-semibold text-gray-400 dark:text-gray-500 block uppercase tracking-wider mb-0.5 select-none">
                              Status
                            </span>
                            <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold mt-0.5 ${
                              req.status === 'Pending'
                                ? 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400'
                                : 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-400'
                            }`}>
                              {req.status}
                            </span>
                          </div>
                        </div>
                      </div>

                      {/* Actions */}
                      <div className="col-span-2 flex items-center justify-end gap-2">
                        {/* View & Respond Button */}
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-8 w-8 rounded-lg text-gray-400 hover:text-black dark:hover:text-white"
                          onClick={() => {
                            setViewingRequest(req);
                            setResponseText(req.response || '');
                          }}
                        >
                          <MessageSquare className="h-4 w-4" />
                        </Button>

                        {/* Delete Button */}
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-8 w-8 rounded-lg text-gray-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-955/20"
                          onClick={() => setDeletingRequest(req)}
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* View & Respond Dialog */}
      <Dialog
        open={!!viewingRequest}
        onOpenChange={open => {
          if (!open) {
            setViewingRequest(null);
            setResponseText('');
          }
        }}
      >
        <DialogContent className="max-w-2xl rounded-[20px] bg-[#F5F5F7] dark:bg-zinc-900 border-none shadow-xl animate-in fade-in-50 duration-150">
          <DialogHeader>
            <DialogTitle className="text-lg font-bold">
              {viewingRequest?.status === 'Pending' ? 'Respond to Support Request' : 'Support Request Details'}
            </DialogTitle>
            <DialogDescription className="text-gray-500 dark:text-gray-400 text-xs">
              View the message body and manage response details.
            </DialogDescription>
          </DialogHeader>

          {viewingRequest && (
            <div className="py-4 space-y-4 max-h-[60vh] overflow-y-auto pr-1">
              {/* Meta Info */}
              <div className="grid grid-cols-2 gap-4 text-sm bg-white dark:bg-gray-905 p-4 rounded-xl border border-black/5 dark:border-white/5">
                <div>
                  <span className="text-[10px] font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider block mb-0.5">From</span>
                  <span className="font-semibold text-gray-800 dark:text-gray-200 select-all">{viewingRequest.email}</span>
                </div>
                <div>
                  <span className="text-[10px] font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider block mb-0.5">Date & Time</span>
                  <span className="font-medium text-gray-700 dark:text-gray-300">{viewingRequest.date} at {viewingRequest.time}</span>
                </div>
                <div className="col-span-2 mt-1">
                  <span className="text-[10px] font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider block mb-0.5">Subject</span>
                  <span className="font-semibold text-gray-800 dark:text-gray-100">{viewingRequest.subject}</span>
                </div>
              </div>

              {/* Message Body */}
              <div className="space-y-1">
                <span className="text-[10px] font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider block">Message</span>
                <div className="bg-white dark:bg-gray-905 p-4 rounded-xl border border-black/5 dark:border-white/5 text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap leading-relaxed shadow-sm min-h-[80px]">
                  {viewingRequest.message}
                </div>
              </div>

              {/* Response Section */}
              <div className="space-y-2 pt-2">
                <span className="text-[10px] font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider block">
                  {viewingRequest.status === 'Responded' ? 'Your Response' : 'Write Response'}
                </span>
                
                {viewingRequest.status === 'Responded' ? (
                  <div className="bg-emerald-50/50 dark:bg-emerald-950/10 border border-emerald-500/20 p-4 rounded-xl text-sm leading-relaxed">
                    <p className="text-gray-700 dark:text-gray-300 whitespace-pre-wrap">{viewingRequest.response}</p>
                    {viewingRequest.respondedAt && (
                      <span className="text-[10px] text-emerald-600 dark:text-emerald-400 block mt-2 font-medium">
                        Sent on {viewingRequest.respondedAt}
                      </span>
                    )}
                  </div>
                ) : (
                  <Textarea
                    placeholder="Type your response to the user here..."
                    value={responseText}
                    onChange={e => setResponseText(e.target.value)}
                    rows={4}
                    className="w-full rounded-xl border border-black/10 dark:border-white/10 bg-white dark:bg-gray-900 p-4 text-sm text-gray-800 placeholder:text-gray-400 dark:text-gray-100 dark:placeholder:text-gray-400 outline-none focus:outline-none focus-visible:outline-none focus:ring-0 focus-visible:ring-0 focus:ring-offset-0 focus-visible:ring-offset-0 focus:border-black/10 dark:focus:border-white/10 focus-visible:border-black/10 dark:focus-visible:border-white/10 shadow-sm transition-all resize-none"
                    disabled={isSubmittingResponse}
                  />
                )}
              </div>
            </div>
          )}

          <DialogFooter className="flex gap-3 justify-end mt-2">
            <DialogClose asChild>
              <Button variant="outline" className="w-36 rounded-lg border-black/10 dark:border-white/10">
                Close
              </Button>
            </DialogClose>
            {viewingRequest?.status === 'Pending' && (
              <Button
                onClick={handleSendResponse}
                disabled={isSubmittingResponse || !responseText.trim()}
                className="w-36 rounded-lg bg-black hover:bg-black/90 text-white dark:bg-white dark:text-black dark:hover:bg-white/90 disabled:opacity-100"
              >
                {isSubmittingResponse ? 'Sending...' : 'Send Response'}
              </Button>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog
        open={!!deletingRequest}
        onOpenChange={open => {
          if (!open) setDeletingRequest(null);
        }}
      >
        <DialogContent className="p-0 overflow-hidden rounded-[20px] max-w-[400px] sm:max-w-[400px] border-none shadow-xl bg-white dark:bg-zinc-900 [&>button]:hidden animate-in fade-in-50 duration-150">
          <div className="px-5 pt-5 pb-4 text-center">
            <DialogTitle className="text-[17px] font-semibold text-black dark:text-white leading-tight text-center">
              Delete Support Request
            </DialogTitle>
            <DialogDescription className="mt-1.5 text-[13px] text-gray-500 dark:text-gray-400 leading-normal px-1 text-center">
              Are you sure you want to remove this support ticket from the inbox?
            </DialogDescription>
          </div>
          <div className="border-t border-black/10 dark:border-white/10 flex h-11">
            <DialogClose asChild>
              <button className="flex-1 text-[15px] font-normal text-black dark:text-white hover:bg-black/5 dark:hover:bg-white/5 active:bg-black/10 dark:active:bg-white/10 transition-colors h-full flex items-center justify-center border-r border-black/10 dark:border-white/10 outline-none">
                Cancel
              </button>
            </DialogClose>
            <DialogClose asChild>
              <button
                onClick={handleDelete}
                className="flex-1 text-[15px] font-medium text-red-500 hover:bg-black/5 dark:hover:bg-white/5 active:bg-black/10 dark:active:bg-white/10 transition-colors h-full flex items-center justify-center outline-none"
              >
                Delete
              </button>
            </DialogClose>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
