import { AdminUser, AdminTenantListItem } from '@/actions/adminActions';

export const DUMMY_USERS: AdminUser[] = [
  {
    _id: 'dummy-1',
    email: 'alex.rivera@enterprise.com',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-1',
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-2',
    email: 'beatrice.vance@startup.io',
    isSubscribed: false,
    role: 'user',
    tenantId: 't-2',
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-3',
    email: 'carter.hayes@technology.net',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-3',
    createdAt: new Date(Date.now() - 12 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-4',
    email: 'diana.prince@wayne.corp',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-4',
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-5',
    email: 'ethan.hunt@impossible.mission',
    isSubscribed: false,
    role: 'user',
    tenantId: 't-5',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'dummy-6',
    email: 'fiona.gallagher@southside.org',
    isSubscribed: false,
    role: 'user',
    tenantId: 't-6',
    createdAt: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-7',
    email: 'george.costanza@vandelay.com',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-7',
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-8',
    email: 'harvey.specter@pearsonhardman.com',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-8',
    createdAt: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-9',
    email: 'irene.adler@bohemia.gov',
    isSubscribed: false,
    role: 'user',
    tenantId: 't-9',
    createdAt: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-10',
    email: 'john.watson@bakerstreet.com',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-10',
    createdAt: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-11',
    email: 'karl.marx@das.kapital',
    isSubscribed: false,
    role: 'user',
    tenantId: 't-11',
    createdAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-12',
    email: 'lois.lane@dailyplanet.press',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-12',
    createdAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-13',
    email: 'michael.scott@dundermifflin.com',
    isSubscribed: false,
    role: 'user',
    tenantId: 't-13',
    createdAt: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-14',
    email: 'nancy.drew@riverheights.detective',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-14',
    createdAt: new Date(Date.now() - 11 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-15',
    email: 'oscar.martinez@accounting.dm',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-15',
    createdAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-16',
    email: 'pam.beesly@art.dm',
    isSubscribed: false,
    role: 'user',
    tenantId: 't-16',
    createdAt: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-17',
    email: 'quentin.tarantino@pulp.fiction',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-17',
    createdAt: new Date(Date.now() - 25 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-18',
    email: 'ryan.howard@wunderkind.dm',
    isSubscribed: false,
    role: 'user',
    tenantId: 't-18',
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-19',
    email: 'sherlock.holmes@bakerstreet.com',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-19',
    createdAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-20',
    email: 'tony.stark@starkindustries.com',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-20',
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-21',
    email: 'ulysses.grant@civilwar.gov',
    isSubscribed: false,
    role: 'user',
    tenantId: 't-21',
    createdAt: new Date(Date.now() - 40 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-22',
    email: 'victor.frankenstein@monster.creations',
    isSubscribed: false,
    role: 'user',
    tenantId: 't-22',
    createdAt: new Date(Date.now() - 18 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-23',
    email: 'wanda.maximoff@avengers.org',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-23',
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-24',
    email: 'xavier.charles@mutant.academy',
    isSubscribed: true,
    role: 'user',
    tenantId: 't-24',
    createdAt: new Date(Date.now() - 16 * 24 * 3600 * 1000).toISOString(),
  },
  {
    _id: 'dummy-25',
    email: 'yvonne.strahovski@chuck.show',
    isSubscribed: false,
    role: 'user',
    tenantId: 't-25',
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
];

export const DUMMY_TENANTS: AdminTenantListItem[] = [
  {
    _id: 'dt-1',
    name: 'Acme Enterprise',
    subdomain: 'acme',
    status: 'active',
    plan: 'growth',
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-1', email: 'alex.rivera@enterprise.com' },
    memberCount: 5,
    usage: { usersCount: 5 },
  },
  {
    _id: 'dt-2',
    name: 'Wayne Enterprises',
    subdomain: 'wayne',
    status: 'active',
    plan: 'enterprise',
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-4', email: 'diana.prince@wayne.corp' },
    memberCount: 8,
    usage: { usersCount: 8 },
  },
  {
    _id: 'dt-3',
    name: 'Stark Industries',
    subdomain: 'stark',
    status: 'active',
    plan: 'growth',
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-20', email: 'tony.stark@starkindustries.com' },
    memberCount: 12,
    usage: { usersCount: 12 },
  },
  {
    _id: 'dt-4',
    name: 'Dunder Mifflin',
    subdomain: 'dunder',
    status: 'suspended',
    plan: 'basic',
    createdAt: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-13', email: 'michael.scott@dundermifflin.com' },
    memberCount: 15,
    usage: { usersCount: 15 },
  },
  {
    _id: 'dt-5',
    name: 'Impossible Mission Force',
    subdomain: 'imf',
    status: 'active',
    plan: 'growth',
    createdAt: new Date().toISOString(),
    ownerId: { _id: 'dummy-5', email: 'ethan.hunt@impossible.mission' },
    memberCount: 4,
    usage: { usersCount: 4 },
  },
  {
    _id: 'dt-6',
    name: 'Vandelay Industries',
    subdomain: 'vandelay',
    status: 'active',
    plan: 'basic',
    createdAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-7', email: 'george.costanza@vandelay.com' },
    memberCount: 2,
    usage: { usersCount: 2 },
  },
  {
    _id: 'dt-7',
    name: 'Pearson Hardman',
    subdomain: 'pearson',
    status: 'active',
    plan: 'enterprise',
    createdAt: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-8', email: 'harvey.specter@pearsonhardman.com' },
    memberCount: 22,
    usage: { usersCount: 22 },
  },
  {
    _id: 'dt-8',
    name: 'Baker Street Detective Agency',
    subdomain: 'bakerstreet',
    status: 'active',
    plan: 'basic',
    createdAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-19', email: 'sherlock.holmes@bakerstreet.com' },
    memberCount: 3,
    usage: { usersCount: 3 },
  },
  {
    _id: 'dt-9',
    name: 'Cyberdyne Systems',
    subdomain: 'cyberdyne',
    status: 'cancelled',
    plan: 'basic',
    createdAt: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-9', email: 'irene.adler@bohemia.gov' },
    memberCount: 6,
    usage: { usersCount: 6 },
  },
  {
    _id: 'dt-10',
    name: 'Oscorp Technologies',
    subdomain: 'oscorp',
    status: 'active',
    plan: 'growth',
    createdAt: new Date(Date.now() - 12 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-3', email: 'carter.hayes@technology.net' },
    memberCount: 14,
    usage: { usersCount: 14 },
  },
  {
    _id: 'dt-11',
    name: 'Initech Corporation',
    subdomain: 'initech',
    status: 'active',
    plan: 'basic',
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-2', email: 'beatrice.vance@startup.io' },
    memberCount: 7,
    usage: { usersCount: 7 },
  },
  {
    _id: 'dt-12',
    name: 'Hooli Inc',
    subdomain: 'hooli',
    status: 'active',
    plan: 'growth',
    createdAt: new Date(Date.now() - 11 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-14', email: 'nancy.drew@riverheights.detective' },
    memberCount: 30,
    usage: { usersCount: 30 },
  },
  {
    _id: 'dt-13',
    name: 'Tyrell Corporation',
    subdomain: 'tyrell',
    status: 'active',
    plan: 'enterprise',
    createdAt: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-16', email: 'pam.beesly@art.dm' },
    memberCount: 18,
    usage: { usersCount: 18 },
  },
  {
    _id: 'dt-14',
    name: 'Umbrella Corporation',
    subdomain: 'umbrella',
    status: 'suspended',
    plan: 'growth',
    createdAt: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-6', email: 'fiona.gallagher@southside.org' },
    memberCount: 25,
    usage: { usersCount: 25 },
  },
  {
    _id: 'dt-15',
    name: 'Gekko & Co',
    subdomain: 'gekko',
    status: 'active',
    plan: 'growth',
    createdAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-15', email: 'oscar.martinez@accounting.dm' },
    memberCount: 9,
    usage: { usersCount: 9 },
  },
  {
    _id: 'dt-16',
    name: 'X-Men Academy',
    subdomain: 'xmen',
    status: 'active',
    plan: 'growth',
    createdAt: new Date(Date.now() - 16 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-24', email: 'xavier.charles@mutant.academy' },
    memberCount: 40,
    usage: { usersCount: 40 },
  },
  {
    _id: 'dt-17',
    name: 'Avengers HQ',
    subdomain: 'avengers',
    status: 'active',
    plan: 'enterprise',
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-23', email: 'wanda.maximoff@avengers.org' },
    memberCount: 15,
    usage: { usersCount: 15 },
  },
  {
    _id: 'dt-18',
    name: 'Vance Refrigeration',
    subdomain: 'vance',
    status: 'active',
    plan: 'basic',
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-25', email: 'yvonne.strahovski@chuck.show' },
    memberCount: 2,
    usage: { usersCount: 2 },
  },
  {
    _id: 'dt-19',
    name: 'Globex Corporation',
    subdomain: 'globex',
    status: 'active',
    plan: 'growth',
    createdAt: new Date(Date.now() - 25 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-17', email: 'quentin.tarantino@pulp.fiction' },
    memberCount: 35,
    usage: { usersCount: 35 },
  },
  {
    _id: 'dt-20',
    name: 'Virtucon Industries',
    subdomain: 'virtucon',
    status: 'active',
    plan: 'basic',
    createdAt: new Date(Date.now() - 18 * 24 * 3600 * 1000).toISOString(),
    ownerId: { _id: 'dummy-22', email: 'victor.frankenstein@monster.creations' },
    memberCount: 4,
    usage: { usersCount: 4 },
  }
];
